/* GENERATED by scripts/gen-themes.mjs — do not edit.
   The themes that ship in styles/themes.css, in gallery order. Emitted from
   the same table that writes the CSS so a label can never name a block that
   does not exist (and vice versa): add a theme to THEMES there and re-run
   `pnpm themes`. */

export interface BuiltinTheme {
  value: string
  label: string
  /** One line for the gallery: what this theme *is*, past its hue. */
  note: string
}

export const BUILTIN_THEMES: readonly BuiltinTheme[] = [
  { value: "default", label: "Default", note: "The app as it ships: warm neutral, soft corners, frosted surfaces." },
  { value: "graphite", label: "Graphite", note: "Cool grey and near-achromatic. Tight corners, one hairline of lift." },
  { value: "ocean", label: "Ocean", note: "Deep blue, generously rounded, frosted glass throughout." },
  { value: "forest", label: "Forest", note: "Green and matte, a serif for headings, room enough for diffs." },
  { value: "ember", label: "Ember", note: "Warm orange, fully rounded, deep shadows and heavy glass." },
  { value: "violet", label: "Violet", note: "Saturated purple on a narrow measure — dramatic and focused." },
  { value: "paper", label: "Paper", note: "Warm off-white, serif body under a display serif. Reads like print." },
  { value: "terminal", label: "Terminal", note: "Monospace everywhere, square, flat, as wide as the window allows." },
  { value: "claude", label: "Claude", note: "Anthropic's warm clay, with a serif for headings." },
  { value: "codex", label: "Codex", note: "OpenAI monochrome, Swiss: square, flat, openly tracked." },
  { value: "gemini", label: "Gemini", note: "Google's blue-violet, capsule shapes, heavy frosted glass." },
  { value: "copilot", label: "Copilot", note: "GitHub blue, restrained corners, a densely setting UI sans." },
]
