import WebSocket from "ws";
import { promises as fs } from "node:fs";
const cfg = JSON.parse(await fs.readFile("./data/config.json","utf8"));
const base = `http://127.0.0.1:${cfg.port}`;
const PID = "2c9d1d3e-0851-4f58-9ea7-bec6985f85d8";
const st = await (await fetch(`${base}/api/projects/${PID}/ide`, {method:"POST", headers:{authorization:`Bearer ${cfg.token}`}})).json();
console.log("fresh key:", st.path);
const url = base.replace("http://","ws://") + st.path + "?type=management&reconnectionToken=" + crypto.randomUUID() + "&reconnection=false&skipWebSocketFrames=false";
const t0 = Date.now();
const ws = new WebSocket(url);
let bytes = 0;
ws.on("open", () => console.log(`+${Date.now()-t0}ms OPEN`));
ws.on("message", (d) => { bytes += d.length; });
ws.on("close", (c, r) => console.log(`+${Date.now()-t0}ms CLOSE code=${c} reason=${r} bytesRx=${bytes}`));
ws.on("error", (e) => console.log(`+${Date.now()-t0}ms ERROR ${e.message}`));
await new Promise(r => setTimeout(r, 20000));
console.log(`+${Date.now()-t0}ms final: readyState=${ws.readyState} (1=OPEN) bytesRx=${bytes}`);
process.exit(0);
