// Direct unit tests for the pure functions in src/acp-bridge.ts:
//   - toWireError: everything thrown flattens to {code, message, data}, and the
//     code survives — -32800 is how a cancellation stays a cancellation
//   - parseSessionNotification: the structural check the rerouted subagent-RFD
//     frames are parsed with — throws the SDK's own invalid-params shape
//   - isModeTwin: the dedup that keeps the permission mode from appearing twice
//     when an agent advertises it both as `modes` and as a select option
//   - isFallbackModelMetadataWarning: the exact Codex fallback-metadata notice
//     a profile opting out of has the bridge drop before it is journaled
//   - the SDK surface: every runtime symbol the server reaches through
//     src/acp.ts still exists — an SDK release that moves one fails here, not
//     in a spawn
//
// `parseSessionNotification` and `isModeTwin` are module-private on purpose, so
// they are extracted from the source verbatim into a throwaway module and
// imported through tsx — a function that moves or is renamed fails this test
// loudly at extraction rather than silently testing nothing.
// Run: pnpm test:acp-units
import assert from "node:assert/strict";
import { readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as acp from "../src/acp.js";

const testDir = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(testDir, "../src/acp-bridge.ts"), "utf8");

/** Slice one top-level `function name(...)` out of the source, brace-balanced
    from its opening line to the first `}` at column 0. */
function extract(name: string): string {
  const start = source.indexOf(`function ${name}(`);
  assert.ok(start >= 0, `acp-bridge.ts no longer declares ${name} — update this test`);
  const end = source.indexOf("\n}", start);
  assert.ok(end > start, `could not find the end of ${name}`);
  return source.slice(start, end + 2);
}

const scratch = join(testDir, ".acp-bridge-extracted.ts");
writeFileSync(
  scratch,
  [
    "// Generated by acp-bridge-units.test.ts — never committed, deleted after import.",
    'import * as acp from "../src/acp.js";',
    "type SessionNotification = { sessionId: string; update: { sessionUpdate: string }; _meta?: Record<string, unknown> | null };",
    extract("parseSessionNotification"),
    extract("isModeTwin"),
    extract("isFallbackModelMetadataWarning"),
    "export { parseSessionNotification, isModeTwin, isFallbackModelMetadataWarning };",
  ].join("\n"),
);

let parseSessionNotification: (params: unknown) => { sessionId: string; update: { sessionUpdate: string } };
let isModeTwin: (option: acp.SessionConfigOption, modeIds: ReadonlySet<string>) => boolean;
let isFallbackModelMetadataWarning: (update: Record<string, unknown>) => boolean;
let toWireError: typeof import("../src/acp-bridge.js").toWireError;
try {
  // Imported through a variable so the type checker does not look for a file
  // that only exists while this test runs.
  ({ parseSessionNotification, isModeTwin, isFallbackModelMetadataWarning } = (await import(scratch)) as {
    parseSessionNotification: typeof parseSessionNotification;
    isModeTwin: typeof isModeTwin;
    isFallbackModelMetadataWarning: typeof isFallbackModelMetadataWarning;
  });
  ({ toWireError } = await import("../src/acp-bridge.js"));
} finally {
  unlinkSync(scratch);
}

let passed = 0;
const failures: string[] = [];
function test(name: string, fn: () => void) {
  try {
    fn();
    passed += 1;
    console.log(`  ✓ ${name}`);
  } catch (error) {
    failures.push(name);
    console.log(`  ✗ ${name}\n    ${error instanceof Error ? (error.stack ?? error.message) : String(error)}`);
  }
}

console.log("acp-bridge units");

// ---- toWireError ----

test("a RequestError keeps its code, message and data", () => {
  const wire = toWireError(acp.RequestError.invalidParams("bad shape"));
  assert.equal(wire.code, -32602);
  assert.match(wire.message, /Invalid params|bad shape/);
  // `data` travels whatever it holds — errors.ts reads it for the detail.
  const detailed = toWireError(acp.RequestError.internalError({ stderr: "boom" }));
  assert.equal(detailed.code, -32603);
  assert.deepEqual(detailed.data, { stderr: "boom" });
});

test("a cancellation stays a cancellation — -32800 is not flattened away", () => {
  const wire = toWireError(new acp.RequestError(-32800, "Cancelled"));
  assert.equal(wire.code, -32800);
});

test("a plain Error becomes -32603 with its message", () => {
  const wire = toWireError(new Error("the agent process is gone"));
  assert.deepEqual(wire, { code: -32603, message: "the agent process is gone" });
});

test("a non-Error throw is stringified, never [object Object] by accident", () => {
  assert.deepEqual(toWireError("plain string"), { code: -32603, message: "plain string" });
  assert.deepEqual(toWireError(42), { code: -32603, message: "42" });
  assert.deepEqual(toWireError(undefined), { code: -32603, message: "undefined" });
});

// ---- parseSessionNotification ----

test("a well-formed notification passes through unchanged", () => {
  const params = {
    sessionId: "child-1",
    update: { sessionUpdate: "subagent_spawned", subagentSessionId: "child-1", name: "step" },
  };
  assert.equal(parseSessionNotification(params), params, "the same object, not a copy");
});

test("a frame without a sessionId is refused as invalid params", () => {
  assert.throws(
    () => parseSessionNotification({ update: { sessionUpdate: "subagent_spawned" } }),
    (error: unknown) => error instanceof acp.RequestError && error.code === -32602,
  );
});

test("a frame whose update carries no sessionUpdate tag is refused", () => {
  assert.throws(
    () => parseSessionNotification({ sessionId: "s", update: {} }),
    (error: unknown) => error instanceof acp.RequestError && error.code === -32602,
  );
  assert.throws(
    () => parseSessionNotification({ sessionId: "s", update: { sessionUpdate: 7 } }),
    (error: unknown) => error instanceof acp.RequestError && error.code === -32602,
  );
});

test("null and non-object params are refused, not dereferenced", () => {
  for (const bad of [null, undefined, "str", 5]) {
    assert.throws(() => parseSessionNotification(bad), acp.RequestError);
  }
});

// ---- isFallbackModelMetadataWarning ----

const FALLBACK_WARNING =
  "Warning: Model metadata for `cmc/deepseek/deepseek-v4-flash-fast` not found. " +
  "Defaulting to fallback metadata; this can degrade performance and cause issues.\n\n";

test("codex's fallback-metadata notice is recognized in a text chunk", () => {
  assert.equal(
    isFallbackModelMetadataWarning({
      sessionUpdate: "agent_message_chunk",
      content: { type: "text", text: FALLBACK_WARNING },
    }),
    true,
  );
});

test("the same wording in a thought chunk is left alone", () => {
  assert.equal(
    isFallbackModelMetadataWarning({
      sessionUpdate: "agent_thought_chunk",
      content: { type: "text", text: FALLBACK_WARNING },
    }),
    false,
  );
});

test("an ordinary assistant chunk passes through unmolested", () => {
  assert.equal(
    isFallbackModelMetadataWarning({
      sessionUpdate: "agent_message_chunk",
      content: { type: "text", text: "Let me look at that file.\n" },
    }),
    false,
  );
});

test("a tool-call update (content is an array) is not mistaken for the notice", () => {
  assert.equal(
    isFallbackModelMetadataWarning({
      sessionUpdate: "tool_call",
      content: [{ type: "text", text: FALLBACK_WARNING }],
    }),
    false,
  );
});

test("a chunk carrying the notice in a flat text field (older adapter) is caught too", () => {
  assert.equal(
    isFallbackModelMetadataWarning({ sessionUpdate: "agent_message_chunk", text: FALLBACK_WARNING }),
    true,
  );
});

// ---- isModeTwin ----

const modeIds = new Set(["default", "acceptEdits", "plan"]);
const select = (values: string[], category?: string): acp.SessionConfigOption =>
  ({
    id: "permission-mode",
    name: "Permission mode",
    type: "select",
    category,
    currentValue: values[0],
    options: values.map((value) => ({ value, name: value })),
  }) as acp.SessionConfigOption;

test("category 'mode' says so outright, whatever the values", () => {
  assert.equal(isModeTwin(select(["anything"], "mode"), modeIds), true);
});

test("an uncategorised select with the identical value set is the same knob", () => {
  assert.equal(isModeTwin(select(["plan", "default", "acceptEdits"]), modeIds), true, "order does not matter");
});

test("grouped options are flattened before comparing", () => {
  const grouped = {
    id: "permission-mode",
    name: "Permission mode",
    type: "select",
    currentValue: "default",
    options: [
      { name: "Common", options: [{ value: "default", name: "Default" }, { value: "acceptEdits", name: "Accept edits" }] },
      { value: "plan", name: "Plan" },
    ],
  } as acp.SessionConfigOption;
  assert.equal(isModeTwin(grouped, modeIds), true);
});

test("a different value set is a different knob", () => {
  assert.equal(isModeTwin(select(["default", "acceptEdits"]), modeIds), false, "a subset is not the mode");
  assert.equal(isModeTwin(select(["default", "acceptEdits", "plan", "extra"]), modeIds), false);
  assert.equal(isModeTwin(select(["low", "medium", "high"]), modeIds), false);
});

test("no modes advertised means nothing can be a twin, category or not", () => {
  assert.equal(isModeTwin(select(["default"], "mode"), new Set()), false);
});

test("a non-select option is never the mode", () => {
  const bool = { id: "x", name: "X", type: "boolean", currentValue: true } as unknown as acp.SessionConfigOption;
  assert.equal(isModeTwin(bool, modeIds), false);
});

// ---- the SDK surface ----
//
// The runtime half of what the server takes from the SDK, as reached through
// the one barrel (src/acp.ts). Types are checked by tsc; these are the values
// — and the method-name table, which is the wire protocol the bridge, the probe
// and the session lister speak. Kept as a list of dotted paths so a rename in
// the SDK names the exact symbol that went missing.

const RUNTIME_SURFACE = [
  "client",
  "agent",
  "ndJsonStream",
  "PROTOCOL_VERSION",
  "RequestError",
  "RequestError.invalidParams",
  "RequestError.internalError",
  "methods.agent.initialize",
  "methods.agent.session.new",
  "methods.agent.session.load",
  "methods.agent.session.list",
  "methods.agent.session.prompt",
  "methods.agent.session.cancel",
  "methods.agent.session.setMode",
  "methods.agent.session.setConfigOption",
  "methods.client.session.update",
  "methods.client.session.requestPermission",
  "methods.client.elicitation.create",
  "methods.client.elicitation.complete",
] as const;

test("every runtime symbol the server uses is still exported by the SDK", () => {
  const missing = RUNTIME_SURFACE.filter((path) => {
    let cursor: unknown = acp;
    for (const key of path.split(".")) {
      if (cursor === null || (typeof cursor !== "object" && typeof cursor !== "function")) return true;
      cursor = (cursor as Record<string, unknown>)[key];
    }
    return cursor === undefined;
  });
  assert.deepEqual(missing, [], `SDK no longer exports: ${missing.join(", ")}`);
});

test("the method table still names the wire strings the fake agent answers to", () => {
  // The fake agent (test/fake-agent.mjs) and the agent runtime match on the
  // raw strings, so an SDK that renamed a method under the same key would
  // break both without a type error anywhere.
  assert.equal(acp.methods.agent.initialize, "initialize");
  assert.equal(acp.methods.agent.session.new, "session/new");
  assert.equal(acp.methods.agent.session.load, "session/load");
  assert.equal(acp.methods.agent.session.list, "session/list");
  assert.equal(acp.methods.agent.session.prompt, "session/prompt");
  assert.equal(acp.methods.agent.session.cancel, "session/cancel");
  assert.equal(acp.methods.agent.session.setMode, "session/set_mode");
  assert.equal(acp.methods.agent.session.setConfigOption, "session/set_config_option");
  assert.equal(acp.methods.client.session.update, "session/update");
  assert.equal(acp.methods.client.session.requestPermission, "session/request_permission");
  assert.equal(acp.methods.client.elicitation.create, "elicitation/create");
  assert.equal(acp.methods.client.elicitation.complete, "elicitation/complete");
  assert.equal(acp.PROTOCOL_VERSION, 1);
});

console.log(`\n${passed} passed${failures.length ? `, ${failures.length} failed: ${failures.join(", ")}` : ""}`);
process.exit(failures.length ? 1 : 0);
